server:
  port: 9095
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  application:
    name: oss-demo

meteor:
  oss:
    enable: true
    file-type-while-list: .png|.jpg|.gif|.pdf|.xlsx|.xls|.csv|.mp4|.avi|.jpeg|.svg
    downloadPath: http://localhost:9095/file/download
  #上传对应本地全路径，注意目录不会自动创建，注意 Win是 \ 且有盘符，linux是 / 无盘符，注意目录权限问题
    nfs:
      path: /Users/sloong/Downloads

